In [20]:
import pymongo
from pymongo import MongoClient
client = MongoClient("localhost", 27017)
db = client["companies"]

from pandas.io.json import json_normalize
import json
import pandas as pd

data = db.nuevas_oficinas2.find()

In [21]:
dataset = pd.DataFrame(list(data))
dataset.head()

,_id,city,country_code,founded_year,geo,latitude,long-lat,longitude,name,total_money_raised,total_offices
0,5d26fafca7c6435d74091fab,Pleasanton,USA,2005,"{u'type': u'Point', u'coordinates': [-121.9049...",37.692934,"-121.904945, 37.692934",-121.904945,Zoho,$0,1
1,5d26fafca7c6435d74091fac,New York City,USA,2007,"{u'type': u'Point', u'coordinates': [-73.98550...",40.757929,"-73.985506, 40.757929",-73.985506,MeetMoi,$5.58M,1
2,5d26fafca7c6435d74091fad,London,GBR,2007,"{u'type': u'Point', u'coordinates': [-6.267494...",53.344104,"-6.267494, 53.344104",-6.267494,Babelgum,$13.2M,1
3,5d26fafca7c6435d74091fae,New York,USA,2006,"{u'type': u'Point', u'coordinates': [-74.00944...",40.746497,"-74.0094471, 40.7464969",-74.009447,Joost,$45M,1
4,5d26fafca7c6435d74091faf,San Francisco,USA,2004,"{u'type': u'Point', u'coordinates': [-122.3945...",37.764726,"-122.394523, 37.764726",-122.394523,Digg,$45M,1

In [22]:
def findNear(geopoint, radio_max_meters=1000):
    return db.nuevas_oficinas2.find({
        "geo": {
         "$near": {
           "$geometry": geopoint,
           "$maxDistance": radio_max_meters,
         }
       }
    })

def media_founded_year(lista_empresas): 
    result = 0
    for empresa in lista_empresas: 
        year = empresa.get('founded_year')
        #print(year, type(year))
        result += year
        
    return result/len(lista_empresas)


#media_founded_year(res)

In [23]:
def calcula(row):
    g=row.get('geo')
    lista=findNear(g)
    lista = list(lista)

    resultado=media_founded_year(lista)
    return resultado

calcula(dataset.loc[4])

2006

In [24]:
dataset['average_founded_year'] = dataset.apply(calcula, axis=1)

In [25]:
dataset

,_id,city,country_code,founded_year,geo,latitude,long-lat,longitude,name,total_money_raised,total_offices,average_founded_year
0,5d26fafca7c6435d74091fab,Pleasanton,USA,2005,"{u'type': u'Point', u'coordinates': [-121.9049...",37.692934,"-121.904945, 37.692934",-121.904945,Zoho,$0,1,2005
1,5d26fafca7c6435d74091fac,New York City,USA,2007,"{u'type': u'Point', u'coordinates': [-73.98550...",40.757929,"-73.985506, 40.757929",-73.985506,MeetMoi,$5.58M,1,2006
2,5d26fafca7c6435d74091fad,London,GBR,2007,"{u'type': u'Point', u'coordinates': [-6.267494...",53.344104,"-6.267494, 53.344104",-6.267494,Babelgum,$13.2M,1,2005
3,5d26fafca7c6435d74091fae,New York,USA,2006,"{u'type': u'Point', u'coordinates': [-74.00944...",40.746497,"-74.0094471, 40.7464969",-74.009447,Joost,$45M,1,2006
4,5d26fafca7c6435d74091faf,San Francisco,USA,2004,"{u'type': u'Point', u'coordinates': [-122.3945...",37.764726,"-122.394523, 37.764726",-122.394523,Digg,$45M,1,2006
5,5d26fafca7c6435d74091fb0,Sunnyvale,USA,2002,"{u'type': u'Point', u'coordinates': [-122.0551...",37.387845,"-122.055197, 37.387845",-122.055197,Plaxo,$28.3M,1,2003
6,5d26fafca7c6435d74091fb1,West Hollywood,USA,2006,"{u'type': u'Point', u'coordinates': [-118.3930...",34.090368,"-118.393064, 34.090368",-118.393064,Geni,$16.5M,1,2005
7,5d26fafca7c6435d74091fb2,New York,USA,2005,"{u'type': u'Point', u'coordinates': [-73.99643...",40.723731,"-73.9964312, 40.7237306",-73.996431,Wetpaint,$39.8M,2,2006
8,5d26fafca7c6435d74091fb3,San Francisco,USA,2006,"{u'type': u'Point', u'coordinates': [-122.4169...",37.776805,"-122.4169244, 37.7768052",-122.416924,Twitter,$1.16B,1,2006
9,5d26fafca7c6435d74091fb4,Menlo Park,USA,2004,"{u'type': u'Point', u'coordinates': [-122.1518...",37.416050,"-122.151801, 37.41605",-122.151801,Facebook,$2.43B,3,2005
10,5d26fafca7c6435d74091fb5,Dublin,IRL,2004,"{u'type': u'Point', u'coordinates': [-6.267494...",53.344104,"-6.267494, 53.344104",-6.267494,Facebook,$2.43B,3,2005
11,5d26fafca7c6435d74091fb6,New York,USA,2004,"{u'type': u'Point', u'coordinates': [-73.97924...",40.755716,"-73.9792469, 40.7557162",-73.979247,Facebook,$2.43B,3,2005
12,5d26fafca7c6435d74091fb7,San Francisco,USA,2006,"{u'type': u'Point', u'coordinates': [-122.3952...",37.778613,"-122.395289, 37.778613",-122.395289,Powerset,$22.5M,1,2005
13,5d26fafca7c6435d74091fb8,Menlo Park,USA,2003,"{u'type': u'Point', u'coordinates': [-122.1694...",37.484130,"-122.169472, 37.48413",-122.169472,Gizmoz,$18.1M,1,2005
14,5d26fafca7c6435d74091fb9,Los Angeles,USA,2005,"{u'type': u'Point', u'coordinates': [-118.4465...",34.057498,"-118.446596, 34.057498",-118.446596,Helio,$0,1,2005
15,5d26fafca7c6435d74091fba,Culver City,USA,2007,"{u'type': u'Point', u'coordinates': [-118.4872...",34.017606,"-118.487267, 34.017606",-118.487267,Mahalo,$21M,1,2005
16,5d26fafca7c6435d74091fbb,Seattle,USA,2005,"{u'type': u'Point', u'coordinates': [-122.3332...",47.603122,"-122.333253, 47.603122",-122.333253,Wetpaint,$39.8M,2,2005
17,5d26fafca7c6435d74091fbc,Austin,USA,2006,"{u'type': u'Point', u'coordinates': [-97.74520...",30.268735,"-97.745209, 30.268735",-97.745209,Thoof,$1M,1,2006
18,5d26fafca7c6435d74091fbd,San Francisco,USA,2007,"{u'type': u'Point', u'coordinates': [-122.4040...",37.789634,"-122.404052, 37.789634",-122.404052,Scribd,$25.8M,1,2005
19,5d26fafca7c6435d74091fbe,New York,USA,2002,"{u'type': u'Point', u'coordinates': [-73.99572...",40.726040,"-73.995722, 40.72604",-73.995722,Meetup,$18.3M,1,2006
20,5d26fafca7c6435d74091fbf,San Francisco,USA,2002,"{u'type': u'Point', u'coordinates': [-122.3930...",37.779558,"-122.393041, 37.779558",-122.393041,Technorati,$32.1M,1,2005
21,5d26fafca7c6435d74091fc0,San Diego,USA,2004,"{u'type': u'Point', u'coordinates': [-117.2083...",32.902266,"-117.20834, 32.902266",-117.208340,Veoh,$69.8M,1,2005
22,5d26fafca7c6435d74091fc1,San Francisco,USA,2006,"{u'type': u'Point', u'coordinates': [-122.4091...",37.788482,"-122.409173, 37.788482",-122.409173,Kyte,$23.4M,1,2005
23,5d26fafca7c6435d74091fc2,0,USA,2007,"{u'type': u'Point', u'coordinates': [-95.71289...",37.090240,"-95.712891, 37.09024",-95.712891,Sparter,$0,1,2005
24,5d26fafca7c6435d74091fc3,San Diego,USA,2006,"{u'type': u'Point', u'coordinates': [-117.0814...",33.022176,"-117.081406, 33.022176",-117.081406,Slacker,$73.1M,1,2006
25,5d26fafca7c6435d74091fc4,San Francisco,USA,2005,"{u'type': u'Point', u'coordinates': [-122.4025...",37.793148,"-122.402567, 37.793148",-122.402567,Wesabe,$4.7M,1,2005
26,5d26fafca7c6435d74091fc5,Mountain View,USA,2002,"{u'type': u'Point', u'coordinates': [-122.0676...",37.390056,"-122.067692, 37.390056",-122.067692,SmugMug,$0,1,2005
27,5d26fafca7c6435d74091fc6,Pleasanton,USA,2005,"{u'type': u'Point', u'coordinates': [-121.9077...",37.697805,"-121.907768, 37.697805",-121.907768,Jangl SMS,$9M,1,2005
28,5d26fafca7c6435d74091fc7,Mountain View,USA,2005,"{u'type': u'Point', u'coordinates': [-122.0899...",37.423390,"-122.0899512, 37.4233896",-122.089951,Jajah,$33M,1,2004
29,5d26fafca7c6435d74091fc8,Tempe,USA,2005,"{u'type': u'Point', u'coordinates': [-111.9387...",33.429859,"-111.938739, 33.429859",-111.938739,LifeLock,$178M,1,2006
...,...,...,...,...,...,...,...,...,...,...,...,...
6659,5d26fafca7c6435d740939b4,PARIS,FRA,2006,"{u'type': u'Point', u'coordinates': [2.3406954...",48.869995,"2.3406954, 48.8699947",2.340695,PubliAtis,€1M,1,2005
6660,5d26fafca7c6435d740939b5,Seattle,USA,2000,"{u'type': u'Point', u'coordinates': [-122.3430...",47.611331,"-122.3430581, 47.6113314",-122.343058,Vigilos,$7.4M,1,2005
6661,5d26fafca7c6435d740939b6,Vancouver,CAN,2009,"{u'type': u'Point', u'coordinates': [-123.1092...",49.282455,"-123.109217, 49.2824551",-123.109217,Tiny Speck,$17.2M,1,2005
6662,5d26fafca7c6435d740939b7,Lisbon,PRT,2007,"{u'type': u'Point', u'coordinates': [-9.146220...",38.752367,"-9.1462209, 38.7523672",-9.146221,My TV Shows,$0,1,2007
6663,5d26fafca7c6435d740939b8,Santa Clara,USA,2004,"{u'type': u'Point', u'coordinates': [-121.9744...",37.377798,"-121.9744545, 37.3777985",-121.974454,OptiMedica,$51M,1,2004
6664,5d26fafca7c6435d740939b9,Fremont,USA,2009,"{u'type': u'Point', u'coordinates': [-121.9178...",37.525246,"-121.9178417, 37.5252461",-121.917842,Advanced Power Projects,$13M,1,2009
6665,5d26fafca7c6435d740939ba,Zaragoza,ESP,2004,"{u'type': u'Point', u'coordinates': [-0.894486...",41.669878,"-0.8944867, 41.6698776",-0.894487,ITERNOVA,$0,2,2004
6666,5d26fafca7c6435d740939bb,London,GBR,2000,"{u'type': u'Point', u'coordinates': [-0.114374...",51.512790,"-0.114374, 51.5127901",-0.114374,Block Shield,$0,1,2005
6667,5d26fafca7c6435d740939bc,Teruel,ESP,2004,"{u'type': u'Point', u'coordinates': [-1.105961...",40.340133,"-1.1059614, 40.3401332",-1.105961,ITERNOVA,$0,2,2004
6668,5d26fafca7c6435d740939bd,Sunnyvale,USA,2005,"{u'type': u'Point', u'coordinates': [-122.0121...",37.374930,"-122.0121486, 37.3749302",-122.012149,Mu-Gahat Enterprises,$0,1,2005
6669,5d26fafca7c6435d740939be,Billerica,USA,2002,"{u'type': u'Point', u'coordinates': [-71.27802...",42.528635,"-71.278022, 42.528635",-71.278022,Luminus Devices,$136M,1,2002
6670,5d26fafca7c6435d740939bf,Kiel,DEU,2004,"{u'type': u'Point', u'coordinates': [10.166515...",54.323738,"10.1665152, 54.323738",10.166515,AwardSpace,$0,1,2004
6671,5d26fafca7c6435d740939c0,Paris,FRA,2008,"{u'type': u'Point', u'coordinates': [2.3389864...",48.831850,"2.3389864, 48.8318497",2.338986,Hellocoton,$0,1,2008
6672,5d26fafca7c6435d740939c1,Sunnyvale,USA,2009,"{u'type': u'Point', u'coordinates': [-122.0368...",37.369195,"-122.036849, 37.369195",-122.036849,InstantQ,$0,1,2006
6673,5d26fafca7c6435d740939c2,Miami,USA,2009,"{u'type': u'Point', u'coordinates': [-80.30633...",25.723408,"-80.306331, 25.723408",-80.306331,SEO Sumo,$0,1,2009
6674,5d26fafca7c6435d740939c3,Toronto,CAN,2008,"{u'type': u'Point', u'coordinates': [-79.40085...",43.676252,"-79.4008589, 43.6762521",-79.400859,Buddhacom,$0,1,2008
6675,5d26fafca7c6435d740939c4,San Mateo,USA,2004,"{u'type': u'Point', u'coordinates': [-122.3015...",37.553121,"-122.301534, 37.553121",-122.301534,NextLabs,$0,1,2004
6676,5d26fafca7c6435d740939c5,London,GBR,2009,"{u'type': u'Point', u'coordinates': [-0.116536...",51.517742,"-0.1165365, 51.5177425",-0.116537,acrossair,$0,1,2006
6677,5d26fafca7c6435d740939c6,Menlo Park,USA,2006,"{u'type': u'Point', u'coordinates': [-122.1817...",37.484616,"-122.181753, 37.484616",-122.181753,Cantimer,$2M,1,2004
6678,5d26fafca7c6435d740939c7,San Clemente,USA,2001,"{u'type': u'Point', u'coordinates': [-117.6077...",33.448010,"-117.607717, 33.44801",-117.607717,Cameron Health,$121M,1,2001
6679,5d26fafca7c6435d740939c8,San Jose,USA,2004,"{u'type': u'Point', u'coordinates': [-121.9291...",37.386417,"-121.92917, 37.386417",-121.929170,Celestial Semiconductor,$2M,1,2005
6680,5d26fafca7c6435d740939c9,Reno,USA,2009,"{u'type': u'Point', u'coordinates': [-119.8120...",39.394564,"-119.8120795, 39.394564",-119.812079,MyChances,$0,2,2009
6681,5d26fafca7c6435d740939ca,Menlo Park,USA,2009,"{u'type': u'Point', u'coordinates': [-122.1802...",37.448491,"-122.1802812, 37.4484914",-122.180281,MyChances,$0,2,2007
6682,5d26fafca7c6435d740939cb,Houston,USA,2000,"{u'type': u'Point', u'coordinates': [-95.50454...",29.848779,"-95.5045451, 29.8487788",-95.504545,EnterSys Group,$0,1,2000
6683,5d26fafca7c6435d740939cc,Brussels,BEL,2009,"{u'type': u'Point', u'coordinates': [4.3464721...",50.839970,"4.3464721, 50.83997",4.346472,Getyoo,€1.13M,1,2009
6684,5d26fafca7c6435d740939cd,Jersey City,USA,2004,"{u'type': u'Point', u'coordinates': [-74.03325...",40.715887,"-74.033251, 40.715887",-74.033251,Axon Solutions,$0,1,2004
6685,5d26fafca7c6435d740939ce,Dublin,USA,2003,"{u'type': u'Point', u'coordinates': [-121.9366...",37.701940,"-121.9366984, 37.7019395",-121.936698,Intergy,$0,1,2003
6686,5d26fafca7c6435d740939cf,Livingston,USA,2002,"{u'type': u'Point', u'coordinates': [-74.32355...",40.793024,"-74.3235539, 40.7930239",-74.323554,AfterLogic,$0,1,2002
6687,5d26fafca7c6435d740939d0,Birmingham,USA,2000,"{u'type': u'Point', u'coordinates': [-86.76130...",33.407786,"-86.7613019, 33.4077856",-86.761302,EnteGreat,$0,1,2000
6688,5d26fafca7c6435d740939d1,KÃ¼ssnacht,CHE,2009,"{u'type': u'Point', u'coordinates': [8.4371634...",47.088219,"8.4371634, 47.0882193",8.437163,Oriact,$0,1,2009

In [26]:
dataset['average_founded_year'].max()

2013

In [27]:
#dataset = dataset[dataset['average_founded_year']==dataset["average_founded_year"].max()]

In [28]:
#df = df.drop(df[df["R1"] == 1].index)
dataset = dataset.drop(dataset[dataset["average_founded_year"] < 2009].index)

In [30]:
dataset

,_id,city,country_code,founded_year,geo,latitude,long-lat,longitude,name,total_money_raised,total_offices,average_founded_year
331,5d26fafca7c6435d740920f6,Los Altos,USA,2010,"{u'type': u'Point', u'coordinates': [-111.9035...",33.817100,"-111.9035, 33.8171",-111.903500,GENWI,$7.1M,1,2010
414,5d26fafca7c6435d74092149,Norderstedt,DEU,2009,"{u'type': u'Point', u'coordinates': [10.023246...",53.707739,"10.023246, 53.707739",10.023246,alluc,$0,1,2009
1046,5d26fafca7c6435d740923c2,West Dundee,USA,2009,"{u'type': u'Point', u'coordinates': [-88.28874...",42.091078,"-88.288749, 42.091078",-88.288749,Crootpad,$0,1,2009
1106,5d26fafca7c6435d740923fe,Oakland,USA,2009,"{u'type': u'Point', u'coordinates': [-122.2148...",37.772323,"-122.214897, 37.772323",-122.214897,Handipoints,$800k,1,2009
1243,5d26fafca7c6435d74092487,Sherman Oaks,USA,2008,"{u'type': u'Point', u'coordinates': [-118.4224...",34.153588,"-118.422495, 34.153588",-118.422495,AudioMicro,$1.25M,1,2009
1940,5d26fafca7c6435d74092740,New York,USA,2009,"{u'type': u'Point', u'coordinates': [-71.24762...",42.275263,"-71.24762, 42.275263",-71.247620,BrandYourself,$1.5M,1,2009
1955,5d26fafca7c6435d7409274f,Van Nuys,USA,2010,"{u'type': u'Point', u'coordinates': [-74.29439...",40.650291,"-74.294395, 40.650291",-74.294395,CollegeConvo,$0,1,2010
1979,5d26fafca7c6435d74092767,Venice,USA,2008,"{u'type': u'Point', u'coordinates': [-118.4567...",33.995974,"-118.456709, 33.995974",-118.456709,PerfectBusiness,$0,1,2009
2029,5d26fafca7c6435d7409279a,Bethesda,USA,2012,"{u'type': u'Point', u'coordinates': [-77.02667...",38.989124,"-77.026676, 38.989124",-77.026676,Carfeine,$0,1,2012
2046,5d26fafca7c6435d740927ab,Santa Monica,USA,2010,"{u'type': u'Point', u'coordinates': [-113.5157...",53.544711,"-113.515769, 53.544711",-113.515769,Titan Gaming,$1M,1,2010
2123,5d26fafca7c6435d740927f8,Alameda,USA,2009,"{u'type': u'Point', u'coordinates': [-122.2747...",37.784240,"-122.274771, 37.78424",-122.274771,BitRock,$0,1,2009
2324,5d26fafca7c6435d740928c1,Seattle,USA,2013,"{u'type': u'Point', u'coordinates': [-93.22650...",44.859587,"-93.226503, 44.859587",-93.226503,Gimigo,$0,1,2013
2361,5d26fafca7c6435d740928e6,Sherman Oaks,USA,2010,"{u'type': u'Point', u'coordinates': [-118.4240...",34.157610,"-118.424058, 34.15761",-118.424058,OTOY,$0,1,2009
2404,5d26fafca7c6435d74092911,Oakland,USA,2007,"{u'type': u'Point', u'coordinates': [-122.2148...",37.772323,"-122.214897, 37.772323",-122.214897,Nibea,$0,1,2009
2427,5d26fafca7c6435d74092928,Jacksonville,USA,2011,"{u'type': u'Point', u'coordinates': [-81.56470...",30.269550,"-81.564709, 30.26955",-81.564709,N-Play,$0,1,2011
2636,5d26fafca7c6435d740929f9,Durham,GBR,2009,"{u'type': u'Point', u'coordinates': [-1.574948...",54.703145,"-1.574948, 54.703145",-1.574948,CompareAway,£500k,1,2009
2778,5d26fafca7c6435d74092a87,Singapore,SGP,2011,"{u'type': u'Point', u'coordinates': [-157.7890...",21.303049,"-157.78907, 21.303049",-157.789070,travelmob,$1M,2,2011
2788,5d26fafca7c6435d74092a91,Detroit,USA,2012,"{u'type': u'Point', u'coordinates': [-83.04591...",42.330165,"-83.045913, 42.330165",-83.045913,Non-Member Films,$0,4,2012
2977,5d26fafca7c6435d74092b4e,Clearwater,USA,2009,"{u'type': u'Point', u'coordinates': [-82.70244...",27.913011,"-82.702449, 27.913011",-82.702449,Inuvo,$4.2M,2,2009
3125,5d26fafca7c6435d74092be3,Singapore,SGP,2011,"{u'type': u'Point', u'coordinates': [-157.7890...",21.303049,"-157.78907, 21.303049",-157.789070,travelmob,$1M,2,2011
3132,5d26fafca7c6435d74092bea,Detroit,USA,2012,"{u'type': u'Point', u'coordinates': [-83.04591...",42.330165,"-83.045913, 42.330165",-83.045913,Non-Member Films,$0,4,2012
3318,5d26fafca7c6435d74092ca4,Clearwater,USA,2009,"{u'type': u'Point', u'coordinates': [-82.70244...",27.913011,"-82.702449, 27.913011",-82.702449,Inuvo,$4.2M,2,2009
3515,5d26fafca7c6435d74092d69,Maarssen,NLD,2012,"{u'type': u'Point', u'coordinates': [5.038078,...",52.126616,"5.038078, 52.126616",5.038078,Navara,$0,1,2012
3656,5d26fafca7c6435d74092df6,Miami,USA,2010,"{u'type': u'Point', u'coordinates': [-80.42416...",25.655899,"-80.424167, 25.655899",-80.424167,Webmoblink,$0,1,2010
3697,5d26fafca7c6435d74092e1f,San Francisco,USA,2009,"{u'type': u'Point', u'coordinates': [-86.05470...",39.905226,"-86.0547016, 39.9052263",-86.054702,Formspring,$14.3M,1,2009
3781,5d26fafca7c6435d74092e73,Quebec,CAN,2009,"{u'type': u'Point', u'coordinates': [-71.23733...",46.808194,"-71.2373393, 46.8081938",-71.237339,Star Fever Agency,$550k,1,2009
3914,5d26fafca7c6435d74092ef8,Muenster,DEU,2010,"{u'type': u'Point', u'coordinates': [7.6267552...",51.963009,"7.6267552, 51.9630088",7.626755,fruux,$0,1,2010
3993,5d26fafca7c6435d74092f47,Manchester,GBR,2013,"{u'type': u'Point', u'coordinates': [-2.243949...",53.483707,"-2.2439492, 53.4837067",-2.243949,Clowdy,$0,1,2013
4137,5d26fafca7c6435d74092fd8,North Haven,USA,2011,"{u'type': u'Point', u'coordinates': [-72.81901...",41.477864,"-72.8190106, 41.4778641",-72.819011,Queralt,$650k,1,2011
4305,5d26fafca7c6435d74093080,Seattle,USA,2009,"{u'type': u'Point', u'coordinates': [-149.8995...",61.216583,"-149.899597, 61.216583",-149.899597,Social1000,$0,1,2009
...,...,...,...,...,...,...,...,...,...,...,...,...
6218,5d26fafca7c6435d740937fb,Rome,ITA,2009,"{u'type': u'Point', u'coordinates': [12.483469...",41.925120,"12.4834691, 41.9251196",12.483469,Stereomood,$0,1,2009
6240,5d26fafca7c6435d74093811,Waterloo,CAN,2009,"{u'type': u'Point', u'coordinates': [-80.53449...",43.477552,"-80.534491, 43.477552",-80.534491,Buddingup,$0,1,2009
6294,5d26fafca7c6435d74093847,London,GBR,2009,"{u'type': u'Point', u'coordinates': [0.0118608...",51.820582,"0.0118608, 51.8205815",0.011861,ipadio,$1.6M,1,2009
6315,5d26fafca7c6435d7409385c,Fort Collins,USA,2009,"{u'type': u'Point', u'coordinates': [-105.0766...",40.593239,"-105.0766501, 40.5932386",-105.076650,Solix Biofuels,$68.8M,1,2009
6338,5d26fafca7c6435d74093873,Laguna Beach,USA,2009,"{u'type': u'Point', u'coordinates': [-117.7769...",33.534155,"-117.7769669, 33.5341548",-117.776967,ResuWe,$0,1,2009
6350,5d26fafca7c6435d7409387f,Columbia,USA,2009,"{u'type': u'Point', u'coordinates': [-81.01831...",34.002737,"-81.018312, 34.002737",-81.018312,Startlike,$0,1,2009
6359,5d26fafca7c6435d74093888,Crystal Lake,USA,2009,"{u'type': u'Point', u'coordinates': [-88.33397...",42.279634,"-88.3339768, 42.2796339",-88.333977,Ray Websmith,$0,1,2009
6378,5d26fafca7c6435d7409389b,Ham,BEL,2009,"{u'type': u'Point', u'coordinates': [5.1730329...",51.096604,"5.1730329, 51.0966039",5.173033,Recreax,$0,1,2009
6396,5d26fafca7c6435d740938ad,Malmö,SWE,2009,"{u'type': u'Point', u'coordinates': [12.995074...",55.605799,"12.9950742, 55.6057989",12.995074,Kvittar,$0,1,2009
6397,5d26fafca7c6435d740938ae,Grand Forks,USA,2009,"{u'type': u'Point', u'coordinates': [-97.05561...",47.909156,"-97.055612, 47.909156",-97.055612,GatherSource,$0,1,2009
6408,5d26fafca7c6435d740938b9,London,GBR,2009,"{u'type': u'Point', u'coordinates': [-0.286770...",51.477098,"-0.2867703, 51.4770982",-0.286770,PicFog,$0,1,2009
6424,5d26fafca7c6435d740938c9,North Brunswick,USA,2009,"{u'type': u'Point', u'coordinates': [-74.47893...",40.455501,"-74.478931, 40.455501",-74.478931,Actinobac Biomed,$600k,1,2009
6439,5d26fafca7c6435d740938d8,Madrid,ESP,2010,"{u'type': u'Point', u'coordinates': [-3.706176...",40.445515,"-3.7061764, 40.4455155",-3.706176,ticketea,$5.73M,1,2010
6456,5d26fafca7c6435d740938e9,Lafayette,USA,2009,"{u'type': u'Point', u'coordinates': [-105.1377...",40.003146,"-105.137715, 40.003146",-105.137715,ZOOMcatalog,$0,1,2009
6459,5d26fafca7c6435d740938ec,Salzburg,AUT,2009,"{u'type': u'Point', u'coordinates': [13.041788...",47.822700,"13.041788, 47.8227",13.041788,Wikitude,$0,1,2009
6461,5d26fafca7c6435d740938ee,Marinette,USA,2009,"{u'type': u'Point', u'coordinates': [-87.63297...",45.085040,"-87.6329743, 45.0850398",-87.632974,Midwest Data Systems,$0,1,2009
6465,5d26fafca7c6435d740938f2,Tucson,USA,2009,"{u'type': u'Point', u'coordinates': [-110.9725...",32.230644,"-110.9725175, 32.2306445",-110.972517,Truckeo,$0,1,2009
6467,5d26fafca7c6435d740938f4,Tulln,AUT,2009,"{u'type': u'Point', u'coordinates': [16.297435...",48.115440,"16.2974355, 48.1154399",16.297435,vooch,$0,1,2009
6499,5d26fafca7c6435d74093914,Monte Sereno,USA,2009,"{u'type': u'Point', u'coordinates': [-121.9867...",37.241813,"-121.986779, 37.241813",-121.986779,Asyus,$0,1,2009
6500,5d26fafca7c6435d74093915,Mayaguez,PRI,2009,"{u'type': u'Point', u'coordinates': [-67.15175...",18.206634,"-67.1517568, 18.2066344",-67.151757,140Ware,$0,1,2009
6511,5d26fafca7c6435d74093920,,USA,2009,"{u'type': u'Point', u'coordinates': [-83.16134...",42.603532,"-83.16134, 42.603532",-83.161340,Delphi,$8M,1,2009
6574,5d26fafca7c6435d7409395f,Troy,USA,2009,"{u'type': u'Point', u'coordinates': [-82.54051...",28.490886,"-82.540512, 28.490886",-82.540512,Outspoken Media,$0,1,2009
6606,5d26fafca7c6435d7409397f,Riga,LVA,2009,"{u'type': u'Point', u'coordinates': [24.099661...",56.953006,"24.0996613, 56.9530061",24.099661,Bonvoyagee,$0,1,2009
6612,5d26fafca7c6435d74093985,Smyrna,USA,2009,"{u'type': u'Point', u'coordinates': [-84.5144,...",33.883700,"-84.5144, 33.8837",-84.514400,Collective Core,$0,1,2009
6631,5d26fafca7c6435d74093998,Oxford,GBR,2009,"{u'type': u'Point', u'coordinates': [-1.258104...",51.771426,"-1.2581049, 51.7714264",-1.258105,Bookwhen,$0,1,2009
6664,5d26fafca7c6435d740939b9,Fremont,USA,2009,"{u'type': u'Point', u'coordinates': [-121.9178...",37.525246,"-121.9178417, 37.5252461",-121.917842,Advanced Power Projects,$13M,1,2009
6673,5d26fafca7c6435d740939c2,Miami,USA,2009,"{u'type': u'Point', u'coordinates': [-80.30633...",25.723408,"-80.306331, 25.723408",-80.306331,SEO Sumo,$0,1,2009
6680,5d26fafca7c6435d740939c9,Reno,USA,2009,"{u'type': u'Point', u'coordinates': [-119.8120...",39.394564,"-119.8120795, 39.394564",-119.812079,MyChances,$0,2,2009
6683,5d26fafca7c6435d740939cc,Brussels,BEL,2009,"{u'type': u'Point', u'coordinates': [4.3464721...",50.839970,"4.3464721, 50.83997",4.346472,Getyoo,€1.13M,1,2009
6688,5d26fafca7c6435d740939d1,KÃ¼ssnacht,CHE,2009,"{u'type': u'Point', u'coordinates': [8.4371634...",47.088219,"8.4371634, 47.0882193",8.437163,Oriact,$0,1,2009

In [31]:
dataset.to_json('afines3.json', orient="records", default_handler=str)

In [98]:
#dataset = dataset[dataset['average_founded_year']==dataset["average_founded_year"].max()]

In [101]:
dataset.to_csv("resultado_empresas", sep='\t', encoding='utf-8')

In [102]:
#dataset.to_json('nuevas_oficinas_geoquery.json', orient="records")

In [62]:

#dataset["average_founded_year"] = dataset["founded_year"].apply(media_founded_year)

In [ ]:
#dataset["founded_year"].value_counts()

In [ ]:
# iterate over rows with iterrows()
#for index, row in flights.head().iterrows():
     # access data using column names
 #    print(index, row['delay'], row['distance'], row['origin'])
    
#for index, row in dataset.head().iterrows():
 #   print(index, row)

In [ ]:
#dataset["average_founded_year"] = media_founded_year(dataset["founded_year"])
#def actualidad_score(col):
 #   actualidad_score = []
  #  for i in range(len(col)):
   #     actualidad_score.append(years_scores.get(col[i]))
    #return actualidad_score
#mydataframe["actualidad_score"] = actualidad_score(mydataframe["founded_year"])

In [ ]:
#media_founded_year(res)

In [ ]:
#dataset.head()

In [ ]:
# https://developers.google.com/maps/documentation/geocoding/intro

In [ ]:
#dataset.shape